# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/kevin/Área de Trabalho/Magos"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/kevin/Área de Trabalho/Magos"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kevin/Área de Trabalho/Magos/CMakeFiles" "/home/kevin/Área de Trabalho/Magos/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kevin/Área de Trabalho/Magos/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named render

# Build rule for target.
render: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 render
.PHONY : render

# fast build rule for target.
render/fast:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/build
.PHONY : render/fast

src/Maze.o: src/Maze.cpp.o

.PHONY : src/Maze.o

# target to build an object file
src/Maze.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Maze.cpp.o
.PHONY : src/Maze.cpp.o

src/Maze.i: src/Maze.cpp.i

.PHONY : src/Maze.i

# target to preprocess a source file
src/Maze.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Maze.cpp.i
.PHONY : src/Maze.cpp.i

src/Maze.s: src/Maze.cpp.s

.PHONY : src/Maze.s

# target to generate assembly for a file
src/Maze.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Maze.cpp.s
.PHONY : src/Maze.cpp.s

src/Render.o: src/Render.cpp.o

.PHONY : src/Render.o

# target to build an object file
src/Render.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Render.cpp.o
.PHONY : src/Render.cpp.o

src/Render.i: src/Render.cpp.i

.PHONY : src/Render.i

# target to preprocess a source file
src/Render.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Render.cpp.i
.PHONY : src/Render.cpp.i

src/Render.s: src/Render.cpp.s

.PHONY : src/Render.s

# target to generate assembly for a file
src/Render.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/Render.cpp.s
.PHONY : src/Render.cpp.s

src/canvas.o: src/canvas.cpp.o

.PHONY : src/canvas.o

# target to build an object file
src/canvas.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/canvas.cpp.o
.PHONY : src/canvas.cpp.o

src/canvas.i: src/canvas.cpp.i

.PHONY : src/canvas.i

# target to preprocess a source file
src/canvas.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/canvas.cpp.i
.PHONY : src/canvas.cpp.i

src/canvas.s: src/canvas.cpp.s

.PHONY : src/canvas.s

# target to generate assembly for a file
src/canvas.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/canvas.cpp.s
.PHONY : src/canvas.cpp.s

src/driver_canvas.o: src/driver_canvas.cpp.o

.PHONY : src/driver_canvas.o

# target to build an object file
src/driver_canvas.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/driver_canvas.cpp.o
.PHONY : src/driver_canvas.cpp.o

src/driver_canvas.i: src/driver_canvas.cpp.i

.PHONY : src/driver_canvas.i

# target to preprocess a source file
src/driver_canvas.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/driver_canvas.cpp.i
.PHONY : src/driver_canvas.cpp.i

src/driver_canvas.s: src/driver_canvas.cpp.s

.PHONY : src/driver_canvas.s

# target to generate assembly for a file
src/driver_canvas.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/driver_canvas.cpp.s
.PHONY : src/driver_canvas.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... render"
	@echo "... src/Maze.o"
	@echo "... src/Maze.i"
	@echo "... src/Maze.s"
	@echo "... src/Render.o"
	@echo "... src/Render.i"
	@echo "... src/Render.s"
	@echo "... src/canvas.o"
	@echo "... src/canvas.i"
	@echo "... src/canvas.s"
	@echo "... src/driver_canvas.o"
	@echo "... src/driver_canvas.i"
	@echo "... src/driver_canvas.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

